<?php

namespace App\Models;

use App\Events\AnImageRecordDeletedFromImagesTable;
use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $fillable = [
        'imageable_id',
        'imageable_type',
        'title',
        'alt',
        'name',
    ];

    protected $casts = [
        'name' => 'array'
    ];

    public function imageable()
    {
        return $this->morphTo('imageable');
    }

    public function getImagePath($size = 'original', $urlFormat = true)
    {
        $imageName = $this->name[$size];
        $path = 'storage/images/';
        $imagePath = $path . $imageName;
        return $urlFormat ? url($imagePath) : $imageName;
    }

    public function getImageableId()
    {
        return $this->imageable_id;
    }

    public function getImageableType()
    {
        return $this->imageable_type;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function getAlt()
    {
        return $this->alt;
    }

    public function getName()
    {
        return $this->name;
    }

    //
    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        self::deleting(function (Image $image) {
            echo 'before run event';
            new AnImageRecordDeletedFromImagesTable($image);
            echo 'after run event';
        });
    }

}
