<?php

namespace App\Models;

use App\Events\NewRateHasBeenCreated;
use App\Events\RateHasBeenUpdated;
use Illuminate\Database\Eloquent\Model;

class PageRate extends Model
{
    protected $table = 'page_rate';

    protected $fillable = [
        'rate',
        'user_id'
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        self::created(function ($pageRate) {
            event(new NewRateHasBeenCreated($pageRate));
        });

        self::updated(function ($pageRate) {
            event(new RateHasBeenUpdated($pageRate));
        });
    }

    public function page()
    {
        return $this->belongsTo(Page::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getPageId()
    {
        return $this->page_id;
    }

    public function getUserId()
    {
        return $this->user_id;
    }

    public function getRate()
    {
        return $this->rate;
    }
}
